export const SUPPORTED_WALLETS = {
    METAMASK_WALLET: 'Metamask Wallet',
    UNISAT_WALLET: 'UniSat Wallet'
}

export const CHAINS = {
    BITCOIN_MAINNET: 'BITCOIN_MAINNET',
    BITCOIN_TESTNET: 'BITCOIN_TESTNET',
    BSC_MAINNET: 'BSC_MAINNET',
    BSC_TESTNET: 'BSC_TESTNET',
    ETH_MAINNET: 'ETH_MAINNET',
    ETH_TESTNET: 'ETH_TESTNET'
}
