const ORDER_STATUS = {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    SHIPPED: 'SHIPPED',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED'
} as const

const WAREHOUSE_TYPE = {
    GENERAL: 'GENERAL',
    REFRIGERATED: 'REFRIGERATED',
    HAZARDOUS: 'HAZARDOUS',
    BULK_STORAGE: 'BULK_STORAGE',
    DISTRIBUTION_CENTER: 'DISTRIBUTION_CENTER'
} as const

const VEHICLE_TYPE = {
    MOTORCYCLE: 'MOTORCYCLE',
    CAR: 'CAR',
    VAN: 'VAN',
    TRUCK: 'TRUCK'
} as const

const DELIVERY_STATUS = {
    PENDING: 'PENDING',
    IN_TRANSIT: 'IN_TRANSIT',
    DELIVERED: 'DELIVERED',
    FAILED: 'FAILED',
    RETURNED: 'RETURNED'
} as const

const SERVICE_TYPE = {
    STANDARD: 'STANDARD',
    EXPRESS: 'EXPRESS',
    SAME_DAY: 'SAME_DAY',
    NEXT_DAY: 'NEXT_DAY',
    INTERNATIONAL: 'INTERNATIONAL',
    ECONOMY: 'ECONOMY'
} as const

const CARGO_TYPE = {
    GENERAL: 'GENERAL',
    FRAGILE: 'FRAGILE',
    PERISHABLE: 'PERISHABLE',
    DANGEROUS: 'DANGEROUS',
    VALUABLE: 'VALUABLE',
    TEMPERATURE_CONTROLLED: 'TEMPERATURE_CONTROLLED',
    OVERSIZED: 'OVERSIZED',
    DOCUMENT: 'DOCUMENT'
} as const

const PAYER_TYPE = {
    SENDER: 'SENDER',
    RECEIVER: 'RECEIVER'
} as const

const PICKUP_TIME_TYPE = {
    EARLY_MORNING: 'EARLY_MORNING',
    MORNING: 'MORNING',
    AFTERNOON: 'AFTERNOON',
    EVENING: 'EVENING'
} as const

export {
    ORDER_STATUS,
    WAREHOUSE_TYPE,
    VEHICLE_TYPE,
    DELIVERY_STATUS,
    SERVICE_TYPE,
    CARGO_TYPE,
    PAYER_TYPE,
    PICKUP_TIME_TYPE
}
